# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the angular-dotnet branch
on:
  push:
    branches: [ angular-dotnet ]
  pull_request:
    branches: [ angular-dotnet ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Use docker login to log into ACR
    - name: Docker login to ACR
      uses: azure/docker-login@v1
      with:
       login-server: ${{secrets.CONTAINER_REGISTRY_NAME}}
       username: ${{secrets.CONTAINER_REGISTRY_USERNAME}}
       password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
     # Build and push the image to Container Registry
    - name: Build and Push to Container Registry
      run: |
           docker build --file=MoviesAPI/Dockerfile -t ${{secrets.CONTAINER_REGISTRY_NAME}}/${{secrets.IMAGE_NAME}}:${{ github.sha }} .
           docker push ${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}           
   
