name: CI

on: 
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@4
     
      # Using docker login to authenticate into Azure CR
      - name: Docker login
        with:
          login-server: ${{secrets.CONTAINER_REGISTRY_NAME}}
          username: ${{secrets.CONTAINER_REGISTRY_USERNAME}}
          password: ${{secrets.CONTAINER_REGISTRY_PASSWORD}}
      
      # Build and push a container to the container registry
      - name: Build and push to the container registry
        run: |
            docker build --file=MoviesAPI/Dockerfile -t ${{secrets.CONTAINER_REGISTRY_NAME}}/${{env.IMAGE_NAME}}:${{github.sha}} .
            docker push ${{secrets.CONTAINER_REGISTRY_NAME}}/${{env.IMAGE_NAME}}:${{github.sha}}
